name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish for Raspberry Pi
      run: dotnet publish -r linux-arm --self-contained false -p:PublishReadyToRun=true -p:PublishSingleFile=true
    - name: Zip Published Files
      run: zip -j -r ${{ github.event.repository.name }}.zip bin/Debug/net6.0/linux-arm/publish/*
    - name: Delete Release
      uses: larryjoelane/delete-release-action@v1.0.24
      with:
        release-name: latest
        token: ${{ github.token }}
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: latest
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload Raspberry Pi artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ github.event.repository.name }}.zip
        asset_name: ${{ github.event.repository.name }}.zip
        asset_content_type: application/gzip
      
